version: "3.8"

services:
  potsgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./app.env
    ports:
      - "6500:5432"
    volumes:
      - postgresDB:/data/postgres
  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    env_file:
      - ./app.env
    ports:
      - "5050:80"
volumes:
  postgresDB:
